CREATE DATABASE THU_NGHIEM
GO
USE  THU_NGHIEM

-- Bảng Users
CREATE TABLE Users
(
  UserID VARCHAR(20) NOT NULL,
  UserName NVARCHAR(100) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(50) NOT NULL,
  Avatar NVARCHAR(255),
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  Status NVARCHAR(50) NOT NULL,
  IsVerified BIT NOT NULL,
  PRIMARY KEY (UserID)
);

-- Bảng Genres
CREATE TABLE Genres
(
  GenreID VARCHAR(20) NOT NULL,
  Name NVARCHAR(100) NOT NULL,
  PRIMARY KEY (GenreID)
);

-- Bảng SearchHistory
CREATE TABLE SearchHistory
(
  SearchID VARCHAR(20) NOT NULL,
  Keyword NVARCHAR(255) NOT NULL,
  SearchAt DATETIME NOT NULL DEFAULT GETDATE(),
  UserID VARCHAR(20) NOT NULL,
  PRIMARY KEY (SearchID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- Bảng Countries
CREATE TABLE Countries
(
  CountryID VARCHAR(20) NOT NULL,
  CountryName NVARCHAR(100) NOT NULL,
  ISOCode NVARCHAR(10),
  PRIMARY KEY (CountryID)
);

-- Bảng Movies
CREATE TABLE Movies
(
  MovieID VARCHAR(20) NOT NULL,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NOT NULL,
  ReleaseDate DATE NOT NULL,
  PosterURL NVARCHAR(255),
  TrailerURL NVARCHAR(255),
  ViewCount INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  Status NVARCHAR(50) NOT NULL,
  VideoURL NVARCHAR(255),
  Duration INT NOT NULL,
  CountryID VARCHAR(20) NOT NULL,
  PRIMARY KEY (MovieID),
  FOREIGN KEY (CountryID) REFERENCES Countries(CountryID)
);

-- Bảng Views
CREATE TABLE Views
(
  ViewID VARCHAR(20) NOT NULL,
  ViewAt DATETIME NOT NULL DEFAULT GETDATE(),
  SessionID NVARCHAR(100),
  IP NVARCHAR(45),
  UserID VARCHAR(20) NOT NULL,
  MovieID VARCHAR(20) NOT NULL,
  PRIMARY KEY (ViewID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

-- Bảng Comment
CREATE TABLE Comment
(
  CommentID VARCHAR(20) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  ParentCommentID VARCHAR(20),
  UserID VARCHAR(20) NOT NULL,
  MovieID VARCHAR(20) NOT NULL,
  PRIMARY KEY (CommentID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

-- Bảng WatchHistory
CREATE TABLE WatchHistory
(
  HistoryID VARCHAR(20) NOT NULL,
  LastWatchedAt DATETIME NOT NULL DEFAULT GETDATE(),
  PositionSeconds INT NOT NULL,
  WatchedPercent FLOAT NOT NULL,
  Completed BIT NOT NULL,
  UserID VARCHAR(20) NOT NULL,
  MovieID VARCHAR(20) NOT NULL,
  PRIMARY KEY (HistoryID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

-- Bảng Favorites
CREATE TABLE Favorites
(
  FavoriteID VARCHAR(20) NOT NULL,
  AddAt DATETIME NOT NULL DEFAULT GETDATE(),
  UserID VARCHAR(20) NOT NULL,
  MovieID VARCHAR(20) NOT NULL,
  PRIMARY KEY (FavoriteID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

-- Bảng Ratings
CREATE TABLE Ratings
(
  RatingID VARCHAR(20) NOT NULL,
  RatingValue INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  UserID VARCHAR(20) NOT NULL,
  MovieID VARCHAR(20) NOT NULL,
  PRIMARY KEY (RatingID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

-- Bảng MovieGenres (bảng liên kết nhiều-nhiều)
CREATE TABLE MovieGenres
(
  MovieID VARCHAR(20) NOT NULL,
  GenreID VARCHAR(20) NOT NULL,
  PRIMARY KEY (MovieID, GenreID),
  FOREIGN KEY (MovieID) REFERENCES Movies(MovieID),
  FOREIGN KEY (GenreID) REFERENCES Genres(GenreID)
);
